function [fitresult, gof] = createFit(meanSignalX)
%CREATEFIT(MEANSIGNALX)
%  Create a fit.
%
%  Data for 'xFit' fit:
%      Y Output: meanSignalX
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Dec-2013 12:05:22


%% Fit: 'xFit'.
[xData, yData] = prepareCurveData( [], meanSignalX );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.309432142296984;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'xFit' );
h = plot( fitresult, xData, yData );
legend( h, 'meanSignalX', 'xFit', 'Location', 'NorthEast' );
% Label axes
ylabel( 'meanSignalX' );
grid on


